language: ruby
bundler_args: --without development production staging --deployment
rvm:
  - 2.2.1
  - ruby-head
before_script:
  - cp config/database.yml.ci config/database.yml
  - mysql -e 'create database master_chef_test'
  - psql -c 'create database master_chef_test' -U postgres
env:
  - DB=postgresql

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
