source 'https://rubygems.org'

group :chef do
  gem 'chef'
  gem 'knife-solo'
  gem 'knife-solo_data_bag'
  gem 'rake'
  gem 'berkshelf'
  gem 'dep-selector-libgecode', github: 'miry/dep-selector-libgecode', branch: 'patch-1'
end
